#!/usr/bin/env /usr/bin/python3
from factorize_all import factorize_all
from sys import argv

if __name__ == "__main__":
    try:
        with open(argv[1]) as file:
            line = file.readline()

            while line != "":
                value = int(line.split('\n')[0])
                factorize_all(value)    
                line = file.readline()
    except:
        pass